---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tic-tac-toe-game
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tic-tac-toe-game
  template:
    metadata:
      labels:
        app: tic-tac-toe-game
    spec:
      containers:
      - name: tic-tac-toe-game
        image: abedjoulany/tic-tac-toe-game:latest
        ports:
        - containerPort: 3000   # Use port 3000
#
---
apiVersion: v1
kind: Service
metadata:
  name: tic-tac-toe-game-service
spec:
  selector:
    app: tic-tac-toe-game
  ports:
  - protocol: TCP
    port: 80                 # Expose port 80
    targetPort: 3000
  type: LoadBalancer
